common_args:
  training_type: "cross_silo"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release
  name: "exp"
  project: "runs/train"
  exist_ok: false

data_args:
  dataset: "freesolv"
  data_cache_dir: ~/fedgraphnn_data/
  part_file:  ~/fedgraphnn_data/partition
  partition_method: "hetero"
  partition_alpha: 0.5

environment_args:
  bootstrap: config/bootstrap.sh

model_args:
  model: "gat"
  hidden_size: 32
  node_embedding_dim: 32
  graph_embedding_dim: 64
  readout_hidden_dim: 64
  alpha: 0.2
  num_heads: 2
  dropout: 0.3
  normalize_features: False
  normalize_adjacency: False
  sparse_adjacency: False

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: 
  client_num_in_total: 1
  client_num_per_round: 1
  comm_round: 100
  epochs: 5
  batch_size: 64
  client_optimizer: sgd
  learning_rate: 0.01
  weight_decay: 0.001
  metric: "rmse"

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 1
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_fedgraphnn_sp

comm_args:
  backend: "MQTT_S3"
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yamls


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_moleculenet