env:
    - ARCH=x86
dist: bionic
os:
    - linux
language: python
sudo: false
python:
    - "3.7.4"
install:
    - "bash CI-install.sh"
script:
    - "bash CI-script-framework.sh"
    - "bash CI-script-fedavg.sh"
    - "bash CI-script-fednas.sh"
    - "bash CI-script-fedavg-robust.sh"
