common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: "../../../data/cifar10"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "resnet56"

train_args:
  federated_optimizer: "FedGKT"
  client_id_list: "[]"
  client_num_in_total: 5
  client_num_per_round: 3
  comm_round: 2
  epochs: 1
  batch_size: 100
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  server_optimizer: sgd
  lr: 0.001
  server_lr: 0.001
  wd: 0.001
  ci: 0
  server_momentum: 0.9
  no_bn_wd: false
  optimizer: "SGD"
  temperature: 100
  whether_training_on_client: false
  epochs_client: 2
  epochs_server: 2
  sweep: 1
  whether_distill_on_the_server: true
  alpha: 0.5 #knowledge distillation parameter

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 5
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_config1_5
  multi_gpu_server: false

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false
