common_args:
  training_type: "cross_device"
  using_mlops: false
  random_seed: 0
  config_version: release

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "cifar"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5
  train_size: 10000
  test_size: 5000

model_args:
  model: "resnet20"
  deeplearning_backend: "mnn"
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.mnn"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[138]"
  client_num_in_total: 1
  client_num_per_round: 1
  comm_round: 3
  epochs: 1
  batch_size: 100
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 1 # this only reflects on the client number, not including the server
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MQTT_S3_MNN"
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yaml

tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_project: fedml
  run_name: fedml_torch_fedavg_cifar_lr