common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "fed_cifar100"
  data_cache_dir: "/home/chaoyanghe/zhtang_FedML/python/fedml/data/fed_cifar100/datasets"
  partition_method: "hetero"
  partition_alpha: 0.1

model_args:
  model: "resnet20"

train_args:
  federated_optimizer: "FedAvg_seq"
  client_id_list: "[]"
  client_num_in_total: 500
  client_num_per_round: 10
  comm_round: 4000
  epochs: 1
  batch_size: 20
  client_optimizer: sgd
  learning_rate: 0.01
  weight_decay: 0.0001

validation_args:
  frequency_of_the_test: 100

device_args:
  worker_num: 8
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
  gpu_util_parse: "localhost:2,1,1,1,1,1,1,1"

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: False
  wandb_entity: automl
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: bench_optim
  wandb_name: fedml_optim_bench
  run_name: fedml_optim_bench
  wandb_only_server: True
  using_mlops: False
  simulation_schedule: "LinearFit-DP"

attack_args:
  enable_attack: false
  attack_type: None

defense_args:
  enable_defense: False
  defense_type: norm_diff_clipping
  norm_bound: 5.0




