common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: "../../../data/cifar10/"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "mobilenet_v3"

train_args:
  federated_optimizer: "FedOpt"
  client_id_list: "[]"
  client_num_in_total: 20
  client_num_per_round: 10
  comm_round: 20
  epochs: 10
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"
  is_mobile: 0

tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_fedavg_cifar10_cnn
  using_mlops: false