common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "YAGO3-10"
  data_cache_dir: "./data/"
  partition_method: "hetero"
  part_algo: "Louvain"
  pred_task: "relation"
  partition_alpha: 100
  ego_number: 10
  hop_number: 2

model_args:
  model: "rgcn"
  hidden_size: 32
  node_embedding_dim: 32
  graph_embedding_dim: 64
  readout_hidden_dim: 64
  n_layers: 5
  alpha: 0.2
  num_heads: 2
  dropout: 0.3
  normalize_features: False
  normalize_adjacency: False
  sparse_adjacency: False

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 4
  comm_round: 100
  epochs: 5
  batch_size: 64
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  metric: "prc-auc"

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 2
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_config1_5_2

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  enable_tracking: false
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_moleculenet