# This is a basic workflow to help you get started with Actions

name: Full End-to-end Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev/v0.7.0 ]
  pull_request:
    branches: [ master, dev/v0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mlops-cli-test"
  mlops-cli-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        arch: [X64, ARM64]
        python-version: ['3.8']
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash
        working-directory: python

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHAOYANG_TOKEN }}
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        #      - name: pip install -e ./
        #        run: |
        #          echo "install pip"
        #          sudo apt-get install python3-pip << eof
        #
        #          y
        #
        #          eof
        #
        #          echo "pip install -e ./"
        #          pip install -e ./

      - name: test sp_fedavg_mnist_lr_example
        run: |
          echo "this is for test sp_fedavg_mnist_lr_example"
          cd examples/simulation/sp_fedavg_mnist_lr_example

          echo "train"
          python torch_fedavg_mnist_lr_step_by_step_example.py --cf fedml_config.yaml
          echo "finish"

      - name: test sp_fedopt_mnist_lr_example
        run: |
          echo "this is for test sp_fedopt_mnist_lr_example"
          cd examples/simulation/sp_fedopt_mnist_lr_example

          echo "train"
          python torch_fedopt_mnist_lr_step_by_step_example.py --cf fedml_config.yaml
          echo "finish"

      - name: test sp_fednova_mnist_lr_example
        run: |
          echo "this is for test sp_fednova_mnist_lr_example"
          cd examples/simulation/sp_fednova_mnist_lr_example

          echo "train"
          python torch_fednova_mnist_lr_step_by_step_example.py --cf fedml_config.yaml
          echo "finish"

      - name: test sp_turboaggregate_mnist_lr_example
        run: |
          echo "this is for test sp_turboaggregate_mnist_lr_example"
          cd examples/simulation/sp_turboaggregate_mnist_lr_example

          echo "train"
          python torch_turboaggregate_mnist_lr_step_by_step_example.py --cf fedml_config.yaml
          echo "finish"

      - name: test sp_hierarchicalfl_mnist_lr_example
        run: |
          echo "this is for test sp_hierarchicalfl_mnist_lr_example"
          cd examples/simulation/sp_hierarchicalfl_mnist_lr_example

          python torch_hierarchicalfl_mnist_lr_step_by_step_example.py --cf fedml_config.yaml

      - name: test sp_vertical_mnist_lr_example
        run: |
          echo "this is for test sp_vertical_mnist_lr_example"
          cd examples/simulation/sp_vertical_mnist_lr_example

          python torch_vertical_mnist_lr_step_by_step_example.py --cf fedml_config.yaml

      - name: test sp_fedsgd_cifar10_resnet20_example
        run: |
          echo "this is for test sp_fedsgd_cifar10_resnet20_example"

          cd examples/simulation/sp_fedsgd_cifar10_resnet20_example

          python sp_fedsgd_cifar10_resnet20_example.py --cf eftopk_config.yaml

      - name: test example B
        run: |
          echo "this is for test example B"
          echo "second line of the script"