name: Pylint - FedML

on:
  pull_request:
    branches: [ master, test/v0.7.0, dev/0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: python
    runs-on: [self-hosted, runner-linux, devops-mpi]
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ X64 ]
        python-version: ["3.8"]
        mpi: [ 'openmpi' ]
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}
    - name: Analysing the code with pylint
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint
        pip install "fedml[gRPC]"
        pip install "fedml[tensorflow]"
        pip install "fedml[jax]"
        pip install "fedml[mxnet]"
        pip install tensorflow_federated
        pip install mxnet
        pip install jax
        pip install ptflops
        pylint --rcfile=build_tools/lint/.pylintrc --disable=C,R,W,I ./
