# This is a basic workflow to help you get started with Actions

name: LightSecAgg-Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  pull_request:
    branches: [ master,  test/v0.7.0, dev/0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cross-silo-horizontal-test:
    defaults:
      run:
        shell: powershell
        working-directory: fedml-devops\python
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        arch: [X64]
        python-version: ['3.8']
        client-index: ['0', '1', '2']
#        exclude:
#          - os: macos-latest
#            python-version: '3.8'
#          - os: windows-latest
#            python-version: '3.6'
    runs-on: [self-hosted, runner-windows, devops]
    timeout-minutes: 15
    steps:
      - name: cleanup running processes
        continue-on-error: true
        run: |
            wmic.exe /interactive:off process where "name='python.exe'" call terminate
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
        with:
          path: fedml-devops
          clean: true
      - name: pip install -e ./
        run: |
          pip install -e ./

      - name: server - cross-silo - ho
        run: |
          cd examples/cross_silo/light_sec_agg_example
          .\run_server.bat cross-silo-lightsecagg-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if:   ${{ matrix.client-index == '0' }}

      - name: client 1 - cross-silo - ho
        run: |
          cd examples/cross_silo/light_sec_agg_example
          .\run_client.bat 1 cross-silo-lightsecagg-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if:   ${{ matrix.client-index == '1' }}

      - name: client 2 - cross-silo - lightsecagg
        run: |
          cd examples/cross_silo/light_sec_agg_example
          .\run_client.bat 2 cross-silo-lightsecagg-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '2' }}