# This is a basic workflow to help you get started with Actions

name: MPI - On Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  push:
    branches: [ master, test/v0.7.0, dev/v0.7.0 ]
  pull_request:
    branches: [ master, test/v0.7.0, dev/v0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # https://github.com/mpi4py/mpi4py/actions/runs/34979774/workflow
  mpi_run:
    runs-on: [self-hosted, runner-linux, devops-mpi]
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      matrix:
        python-version: [3.8]
        mpi: [mpich]
#        mpi: [mpich, openmpi]
        os: [ ubuntu-latest ]
#        include:
#        - os: ubuntu-latest
#          mpi: mpich
#          install-mpi: sudo apt install -y mpich libmpich-dev
#        - os: ubuntu-latest
#          mpi: openmpi
#          install-mpi: sudo apt install -y openmpi-bin libopenmpi-dev
    steps:
    - uses: actions/checkout@v2
    - name: Install MPI
      run: ${{ matrix.install-mpi }}
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packaging tools
      run:  python -m pip install --upgrade setuptools pip wheel
    - name: Install build dependencies
      run:  python -m pip install --upgrade cython
    - name: Build package
      run:  python -m pip wheel -vvv --wheel-dir=dist .
    - name: Install test dependencies
      run:  python -m pip install --upgrade numpy

    - name: pip install -e ./
      run: |
        pip install -e ./

    - name: Test package
      run: |
        cd examples/simulation/mpi_torch_fedavg_mnist_lr_example
        sh run_custom_data_and_model_example.sh 4
    - name: Uninstall package after testing
      run:  python -m pip uninstall --yes mpi4py