# This is a basic workflow to help you get started with Actions

name: PIP, CLI, SP - On Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  push:
    branches: [ master,  test/v0.7.0, dev/v0.7.0 ]
  pull_request:
    branches: [ master,  test/v0.7.0, dev/v0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pip-install-fedml-and-test-sp:
    defaults:
      run:
        shell: powershell
        working-directory: fedml-devops\python
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        arch: [X64]
        python-version: ['3.8']
#        exclude:
#          - os: macos-latest
#            python-version: '3.8'
#          - os: windows-latest
#            python-version: '3.6'
    runs-on: [self-hosted, runner-windows, devops]
    timeout-minutes: 10
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # https://github.com/actions/checkout/issues/116#issuecomment-644419389
      - uses: actions/checkout@v3
        with:
          path: fedml-devops
          clean: true
      - name: pip install -e ./
        run: |
          pip install -e ./

      - name: test "fedml login" and "fedml build"
        run: |
          cd tests/smoke_test/cli
          .\login.bat
          .\build.bat
      - name: test simulation-sp
        run: |
          cd quick_start/parrot
          python torch_fedavg_mnist_lr_one_line_example.py --cf fedml_config.yaml
          python torch_fedavg_mnist_lr_custum_data_and_model_example.py --cf fedml_config.yaml
