# This is a basic workflow to help you get started with Actions

name: ML-Engines-Win

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  pull_request:
    branches: [ master,  test/v0.7.0, dev/0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tf-ml-engines-test:
    defaults:
      run:
        shell: powershell
        working-directory: fedml-devops\python
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        arch: [ X64 ]
        python-version: [ '3.8' ]
    runs-on: [self-hosted, runner-windows, devops]
    timeout-minutes: 15
    steps:
      - name: cleanup running processes
        continue-on-error: true
        run: |
          wmic.exe /interactive:off process where "name='python.exe'" call terminate
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
        with:
          path: fedml-devops
          clean: true
      - name: pip install -e ./
        run: |
          pip install -e ./
          pip install -e '.[tensorflow]'

      - name: server - tensorflow - fedavg
        run: |
          cd examples/cross_silo/tf_mqtt_s3_fedavg_mnist_lr_example
          python tf_server.py --cf config/fedml_config.yaml --rank 0 --role server --run_id tf-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if:   ${{ matrix.client-index == '0' }}

      - name: client 1 - tensorflow - fedavg
        run: |
          cd examples/cross_silo/tf_mqtt_s3_fedavg_mnist_lr_example
          python3 tf_client.py --cf config/fedml_config.yaml --rank 1 --role client --run_id tf-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if:   ${{ matrix.client-index == '1' }}

      - name: client 2 - tensorflow - fedavg
        run: |
          cd examples/cross_silo/tf_mqtt_s3_fedavg_mnist_lr_example
          python3 tf_client.py --cf config/fedml_config.yaml --rank 2 --role client --run_id tf-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '2' }}

  jax-ml-engines-test:
    defaults:
      run:
        shell: powershell
        working-directory: fedml-devops\python
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        arch: [ X64 ]
        python-version: [ '3.8' ]
    runs-on: [ self-hosted, runner-windows, devops ]
    timeout-minutes: 15
    steps:
      - name: cleanup running processes
        continue-on-error: true
        run: |
          wmic.exe /interactive:off process where "name='python.exe'" call terminate
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
        with:
          path: fedml-devops
          clean: true
      - name: pip install -e ./
        run: |
          pip install -e ./
          pip install -e '.[jax]'

      - name: server - jax - fedavg
        run: |
          cd examples/cross_silo/jax_haiku_mqtt_s3_fedavg_mnist_lr_example
          python tf_server.py --cf config/fedml_config.yaml --rank 0 --role server --run_id jax-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '0' }}

      - name: client 1 - jax - fedavg
        run: |
          cd examples/cross_silo/jax_haiku_mqtt_s3_fedavg_mnist_lr_example
          python3 tf_client.py --cf config/fedml_config.yaml --rank 1 --role client --run_id jax-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '1' }}

      - name: client 2 - jax - fedavg
        run: |
          cd examples/cross_silo/jax_haiku_mqtt_s3_fedavg_mnist_lr_example
          python3 tf_client.py --cf config/fedml_config.yaml --rank 2 --role client --run_id jax-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '2' }}

  mxnet-ml-engines-test:
    defaults:
      run:
        shell: powershell
        working-directory: fedml-devops\python
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        arch: [ X64 ]
        python-version: [ '3.8' ]
    runs-on: [ self-hosted, runner-windows, devops ]
    timeout-minutes: 15
    steps:
      - name: cleanup running processes
        continue-on-error: true
        run: |
          wmic.exe /interactive:off process where "name='python.exe'" call terminate
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
        with:
          path: fedml-devops
          clean: true
      - name: pip install -e ./
        run: |
          pip install -e ./
          pip install -e '.[mxnet]'

      - name: server - mxnet - fedavg
        run: |
          cd examples/cross_silo/mxnet_mqtt_s3_fedavg_mnist_lr_example
          python tf_server.py --cf config/fedml_config.yaml --rank 0 --role server --run_id mxnet-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '0' }}

      - name: client 1 - mxnet - fedavg
        run: |
          cd examples/cross_silo/mxnet_mqtt_s3_fedavg_mnist_lr_example
          python3 tf_client.py --cf config/fedml_config.yaml --rank 1 --role client --run_id mxnet-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '1' }}

      - name: client 2 - mxnet - fedavg
        run: |
          cd examples/cross_silo/mxnet_mqtt_s3_fedavg_mnist_lr_example
          python3 tf_client.py --cf config/fedml_config.yaml --rank 2 --role client --run_id mxnet-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
        if: ${{ matrix.client-index == '2' }}
