common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "release"
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: alex-test-prj
  mlops_run_name: fedml_torch_fedavg_mnist_lr_2

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 10
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_tracking: true
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false